name: Build LaTeX document
on:
  push:
    tags:
      - 'v*.*'

env:
  FILE_NAME: main                               # Replace main with file name of main file
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: $FILE_NAME.tex

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "main.pdf, LICENSE"        # This is a hack util variables work here: main should also be replaced
