name: Ntfy-Notification

on:
  workflow_run:
    workflows: [Build LaTeX document]
    types:
      - completed
      
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Successfull message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \                   # Add to secrets in repository
          -H "Title: Project compiled successfully" \     # Change Project to current project
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.workflow_run.conclusion }}' \
          ${{ secrets.NTFY_URL }}                         # Add to secrets in repository
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failed message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \                   # Add to secrets in repository
          -H "Title: Project Compilation failed" \        # Change Project to current project
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.workflow_run.conclusion }}' \
          ${{ secrets.NTFY_URL }}                         # Add to secrets in repository
